"""Alembic environment — async-compatible, dual-mode.

Two ways this env is driven:

1. **Embedded (app startup).** :func:`backend.db.database.init_db` opens a
   connection on the application's ``create_async_engine`` and, inside
   ``run_sync``, hands the resulting *sync* Connection to Alembic via
   ``config.attributes["connection"]``. We run migrations on that shared
   connection — no second engine, and (critically) no nested event loop, so
   this works for both ``aiosqlite`` and ``asyncpg`` without pulling in a
   separate sync driver.

2. **Standalone (``alembic`` CLI).** No connection is pre-supplied, so we build
   our own async engine from the URL and drive it with ``run_sync``. This is
   the path used by ``alembic upgrade`` / ``alembic downgrade`` during
   development and by the downgrade tests.

``target_metadata`` is wired to the app's ``Base.metadata`` so future
``alembic revision --autogenerate`` works (Phases 1C/1D add tables). The
current v0.14.4 schema is captured as hand-written baseline revisions rather
than autogenerated — see the two files under ``versions/``.
"""
from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from backend.config import settings
from backend.db.models import Base

config = context.config

# Only configure logging from the ini for standalone CLI runs. When embedded in
# the app the connection is pre-supplied and the app owns logging config.
if config.config_file_name is not None and config.attributes.get("connection") is None:
    try:
        fileConfig(config.config_file_name)
    except (KeyError, OSError):
        pass

target_metadata = Base.metadata


def _database_url() -> str:
    """Prefer an explicit ini/CLI URL, else the app's configured async URL."""
    return config.get_main_option("sqlalchemy.url") or settings.database_url


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        # Batch (table-recreate) mode makes ALTERs portable to older SQLite,
        # which lacks native DROP/ALTER COLUMN. No-op on other dialects.
        render_as_batch=connection.dialect.name == "sqlite",
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_offline() -> None:
    """Emit SQL to stdout (``alembic upgrade --sql``) without a DB connection."""
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Standalone path: build an async engine and run migrations via run_sync."""
    connectable = async_engine_from_config(
        {"sqlalchemy.url": _database_url()},
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    connection = config.attributes.get("connection", None)
    if connection is not None:
        # Embedded: the app already provided a live (sync) connection.
        do_run_migrations(connection)
    else:
        asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
